name: Bug Report
description: Template to report a bug.
title: "[BUG] Bug Title"
labels: [bug]
assignees: [username]

body:
  - type: markdown
    attributes:
      description: Describe the bug clearly and concisely.

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: "1. Step 1\n2. Step 2\n3. Step 3"

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      placeholder: "Describe what you expected to happen."

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      placeholder: "Describe what actually happened."